name: 9tailors
companyName: 9tailors, LLC
tagline: Some descriptive tag line
url: http://9tailors.com
favicon: http://res.cloudinary.com/l9tl/v1472846223/identity/short-logo.png
telephone: 617.286.6135
emails:
  info: info@9tailors.com
  customerservice: customerservice@9tailors.com
  weddings: weddings@9tailors.com
